/**
 * route.ts — NextAuth.js catch-all route handler.
 *
 * Exposes the Auth.js endpoints (sign-in, callback, session, CSRF, sign-out)
 * under /api/auth/*. The handlers are generated by the full NextAuth config; we
 * destructure GET/POST off them per the v5 convention.
 */
import { handlers } from '@/lib/auth'

export const { GET, POST } = handlers
