/**
 * route.ts — NextAuth.js catch-all route handler.
 *
 * Exposes the Auth.js endpoints (sign-in, callback, session, CSRF, sign-out)
 * under /api/auth/*. The handlers are generated by the full NextAuth config and
 * simply re-exported here per the v5 convention.
 */
export { GET, POST } from '@/lib/auth'
